version: 2
updates:
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - android
  - package-ecosystem: gradle
    directory: /voice_assistant
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - voice-assistant
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - web
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
